import React,{useEffect,useState} from "react";
import {createInvoice,createPayment,getAccounts,getAging,getInvoices,getParties,getPayments,postInvoice,postPayment,cancelInvoice,cancelPayment,allocatePayment,type Invoice,type Payment} from "./api";

const money=(v:any)=>Number(v||0).toLocaleString("ar-YE",{minimumFractionDigits:2,maximumFractionDigits:2});
export default function ArApPage(){
 const [invoices,setInvoices]=useState<Invoice[]>([]),[payments,setPayments]=useState<Payment[]>([]),[parties,setParties]=useState<any[]>([]),[accounts,setAccounts]=useState<any[]>([]),[aging,setAging]=useState<any>(null),[tab,setTab]=useState<"invoices"|"payments">("invoices"),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 const [alloc,setAlloc]=useState<any>({payment_id:"",invoice_id:"",amount:""});
 const [inv,setInv]=useState<any>({invoice_number:"",invoice_type:"sales",party_id:"",invoice_date:new Date().toISOString().slice(0,10),due_date:"",description:"",total_amount:"",receivable_account_id:"",revenue_account_id:""});
 const [pay,setPay]=useState<any>({payment_number:"",payment_type:"receipt",party_id:"",payment_date:new Date().toISOString().slice(0,10),amount:"",source_account_id:"",target_account_id:"",description:""});
 async function load(){try{const [i,p,ps,as,ag]=await Promise.all([getInvoices({}),getPayments({}),getParties(),getAccounts(),getAging("sales")]);setInvoices(i);setPayments(p);setParties(ps);setAccounts(as);setAging(ag)}catch(e){setMsg(e instanceof Error?e.message:"تعذر تحميل البيانات")}}
 useEffect(()=>{load()},[]);
 const setI=(k:string,v:any)=>setInv((x:any)=>({...x,[k]:v}),),setP=(k:string,v:any)=>setPay((x:any)=>({...x,[k]:v}));
 async function act(fn:()=>Promise<any>){setBusy(true);setMsg("");try{await fn();await load();setMsg("تم تنفيذ العملية بنجاح")}catch(e){setMsg(e instanceof Error?e.message:"تعذر تنفيذ العملية")}finally{setBusy(false)}}
 const customers=parties.filter(p=>["customer","agent"].includes(p.party_type)),suppliers=parties.filter(p=>["supplier","agent"].includes(p.party_type));
 const receivable=accounts.filter(a=>["asset","liability"].includes(a.account_type)),income=accounts.filter(a=>["revenue","expense","cost_of_service"].includes(a.account_type));
 return <div className="panel" dir="rtl">
  <div className="panel-head"><div><span className="eyebrow">الذمم والمدفوعات</span><h3>الحسابات المدينة والدائنة</h3><p>فواتير العملاء والموردين، القبض والصرف والتخصيص والمتأخرات.</p></div></div>
  {msg&&<div className="notice">{msg}</div>}
  <div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:14}}><button className={tab==="invoices"?"primary":"secondary"} onClick={()=>setTab("invoices")}>الفواتير</button><button className={tab==="payments"?"primary":"secondary"} onClick={()=>setTab("payments")}>المدفوعات</button><button className="secondary" onClick={()=>act(async()=>{const x=await getAging("sales");setAging(x)})}>تحديث أعمار الذمم</button></div>
  {tab==="invoices"?<><div className="form-grid">
   <label>رقم الفاتورة<input value={inv.invoice_number} onChange={e=>setI("invoice_number",e.target.value)}/></label>
   <label>النوع<select value={inv.invoice_type} onChange={e=>setI("invoice_type",e.target.value)}><option value="sales">مبيعات / عميل</option><option value="purchase">مشتريات / مورد</option></select></label>
   <label>الطرف<select value={inv.party_id} onChange={e=>setI("party_id",e.target.value)}><option value="">اختر</option>{(inv.invoice_type==="sales"?customers:suppliers).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
   <label>تاريخ الفاتورة<input type="date" value={inv.invoice_date} onChange={e=>setI("invoice_date",e.target.value)}/></label>
   <label>الاستحقاق<input type="date" value={inv.due_date} onChange={e=>setI("due_date",e.target.value)}/></label>
   <label>المبلغ<input type="number" min="0" step="0.01" value={inv.total_amount} onChange={e=>setI("total_amount",e.target.value)}/></label>
   <label>حساب الذمم<select value={inv.receivable_account_id} onChange={e=>setI("receivable_account_id",e.target.value)}><option value="">اختر</option>{receivable.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name_ar}</option>)}</select></label>
   <label>حساب الإيراد/التكلفة<select value={inv.revenue_account_id} onChange={e=>setI("revenue_account_id",e.target.value)}><option value="">اختر</option>{income.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name_ar}</option>)}</select></label>
   <label style={{gridColumn:"1/-1"}}>البيان<input value={inv.description} onChange={e=>setI("description",e.target.value)}/></label>
  </div><button className="primary" disabled={busy} onClick={()=>act(()=>createInvoice({...inv,party_id:Number(inv.party_id),total_amount:Number(inv.total_amount),receivable_account_id:Number(inv.receivable_account_id),revenue_account_id:Number(inv.revenue_account_id),due_date:inv.due_date||null}))}>حفظ فاتورة كمسودة</button>
  <div className="table-wrap"><table><thead><tr><th>الرقم</th><th>النوع</th><th>الطرف</th><th>الإجمالي</th><th>المتبقي</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{invoices.map(x=><tr key={x.id}><td>{x.invoice_number}</td><td>{x.invoice_type==="sales"?"مبيعات":"مشتريات"}</td><td>{parties.find(p=>p.id===x.party_id)?.name||x.party_id}</td><td>{money(x.total_amount)}</td><td>{money(x.remaining_amount)}</td><td>{x.status}</td><td>{x.status==="draft"?<button className="secondary" onClick={()=>act(()=>postInvoice(x.id))}>ترحيل</button>:x.status==="posted"?<button className="danger" onClick={()=>act(()=>cancelInvoice(x.id))}>إلغاء</button>:null}</td></tr>)}</tbody></table></div>
 </>:<><div className="form-grid">
   <label>رقم العملية<input value={pay.payment_number} onChange={e=>setP("payment_number",e.target.value)}/></label>
   <label>النوع<select value={pay.payment_type} onChange={e=>setP("payment_type",e.target.value)}><option value="receipt">سند قبض</option><option value="payment">سند صرف</option><option value="transfer">تحويل داخلي</option></select></label>
   <label>الطرف<select value={pay.party_id} onChange={e=>setP("party_id",e.target.value)}><option value="">بدون طرف</option>{parties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
   <label>التاريخ<input type="date" value={pay.payment_date} onChange={e=>setP("payment_date",e.target.value)}/></label>
   <label>المبلغ<input type="number" min="0" step="0.01" value={pay.amount} onChange={e=>setP("amount",e.target.value)}/></label>
   <label>حساب المصدر<select value={pay.source_account_id} onChange={e=>setP("source_account_id",e.target.value)}><option value="">اختر</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name_ar}</option>)}</select></label>
   <label>حساب الهدف<select value={pay.target_account_id} onChange={e=>setP("target_account_id",e.target.value)}><option value="">اختر</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name_ar}</option>)}</select></label>
   <label style={{gridColumn:"1/-1"}}>البيان<input value={pay.description} onChange={e=>setP("description",e.target.value)}/></label>
  </div><button className="primary" disabled={busy} onClick={()=>act(()=>createPayment({...pay,party_id:pay.party_id?Number(pay.party_id):null,amount:Number(pay.amount),source_account_id:Number(pay.source_account_id),target_account_id:Number(pay.target_account_id)}))}>حفظ العملية كمسودة</button>
  <div className="panel" style={{marginTop:16}}><div className="panel-head"><div><span className="eyebrow">التسوية</span><h3>تخصيص دفعة لفاتورة</h3><p>اربط سند القبض أو الصرف بالفاتورة لتحديث الرصيد تلقائيًا.</p></div></div><div className="form-grid"><label>الدفعة<select value={alloc.payment_id} onChange={e=>setAlloc((x:any)=>({...x,payment_id:e.target.value}))}><option value="">اختر دفعة</option>{payments.filter(x=>x.status==="posted"&&Number(x.remaining_amount)>0&&x.payment_type!=="transfer").map(x=><option key={x.id} value={x.id}>{x.payment_number} — {money(x.remaining_amount)}</option>)}</select></label><label>الفاتورة<select value={alloc.invoice_id} onChange={e=>setAlloc((x:any)=>({...x,invoice_id:e.target.value}))}><option value="">اختر فاتورة</option>{invoices.filter(x=>x.status==="posted"&&Number(x.remaining_amount)>0).map(x=><option key={x.id} value={x.id}>{x.invoice_number} — {money(x.remaining_amount)}</option>)}</select></label><label>مبلغ التخصيص<input type="number" min="0" step="0.01" value={alloc.amount} onChange={e=>setAlloc((x:any)=>({...x,amount:e.target.value}))}/></label></div><button className="primary" disabled={busy} onClick={()=>act(()=>allocatePayment(Number(alloc.payment_id),{invoice_id:Number(alloc.invoice_id),amount:Number(alloc.amount)}))}>تخصيص الدفعة</button></div>
  <div className="table-wrap"><table><thead><tr><th>الرقم</th><th>النوع</th><th>الطرف</th><th>المبلغ</th><th>غير مخصص</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{payments.map(x=><tr key={x.id}><td>{x.payment_number}</td><td>{x.payment_type}</td><td>{x.party_id||"—"}</td><td>{money(x.amount)}</td><td>{money(x.remaining_amount)}</td><td>{x.status}</td><td>{x.status==="draft"?<button className="secondary" onClick={()=>act(()=>postPayment(x.id))}>ترحيل</button>:x.status==="posted"?<button className="danger" onClick={()=>act(()=>cancelPayment(x.id))}>إلغاء</button>:null}</td></tr>)}</tbody></table></div>
 </>}
 {aging&&<div className="summary-grid" style={{marginTop:16}}>{Object.entries(aging.buckets||{}).map(([k,v])=><div className="stat" key={k}><span>{k==="current"?"غير متأخر":k}</span><strong>{money(v)}</strong></div>)}</div>}
 </div>
}
