import React, { useEffect, useMemo, useState } from "react";
import { createHajjBooking, createHajjQuota, createParty, createPilgrim, createVoucher, getAccounts, getFinancial, getHajjBookings, getHajjQuotas, getParties, postHajjBooking, postVoucher, type HajjQuota, type Booking, type Program, type Pilgrim } from "./api";

const money = (v: string | number) => Number(v || 0).toLocaleString("ar-YE", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export default function HajjPage({ programs, pilgrims, suppliers, customers }: { programs: Program[]; pilgrims: Pilgrim[]; suppliers: any[]; customers: any[] }) {
  const [quotas, setQuotas] = useState<HajjQuota[]>([]), [bookings, setBookings] = useState<Booking[]>([]), [agents, setAgents] = useState<any[]>([]), [accounts, setAccounts] = useState<any[]>([]), [financial, setFinancial] = useState<any[]>([]), [message, setMessage] = useState(""), [error, setError] = useState("");
  const [pilgrimForm, setPilgrimForm] = useState({ full_name: "", passport_number: "", nationality: "", phone: "" });
  const [quotaForm, setQuotaForm] = useState({ name_ar: "حصة الحج", season: "", supplier_id: "", total_units: "118", unit_cost: "" });
  const [agentForm, setAgentForm] = useState({ name: "", code: "", phone: "", account_id: "" });
  const [bookingForm, setBookingForm] = useState({ program_id: "", pilgrim_id: "", quota_id: "", party_mode: "agent", agent_id: "", customer_id: "", sale_price: "", supplier_cost: "" });
  const [receiptForm, setReceiptForm] = useState({ booking_id: "", financial_account_id: "", amount: "", date: new Date().toISOString().slice(0, 10), description: "تحصيل من خدمة حج" });
  const hajjPrograms = useMemo(() => programs.filter(p => p.program_type === "hajj" && p.is_active), [programs]);
  const selectedQuota = quotas.find(q => q.id === Number(bookingForm.quota_id));
  const selectedBooking = bookings.find(b => b.id === Number(receiptForm.booking_id));
  const selectedAgent = agents.find(a => a.id === Number(selectedBooking?.agent_id));

  async function refresh() {
    try { const [q, b, a, ac, fa] = await Promise.all([getHajjQuotas(), getHajjBookings(), getParties("agent"), getAccounts(), getFinancial()]); setQuotas(q); setBookings(b); setAgents(a); setAccounts(ac); setFinancial(fa); setError(""); }
    catch (e) { setError(e instanceof Error ? e.message : "تعذر تحميل بيانات الحج"); }
  }
  useEffect(() => { refresh(); }, []);
  async function savePilgrim(e: React.FormEvent) { e.preventDefault(); setMessage(""); setError(""); try { await createPilgrim({ ...pilgrimForm, passport_number: pilgrimForm.passport_number || undefined, nationality: pilgrimForm.nationality || undefined, phone: pilgrimForm.phone || undefined }); setPilgrimForm({ full_name:"", passport_number:"", nationality:"", phone:"" }); setMessage("تم تسجيل الحاج."); window.location.reload(); } catch(e){ setError(e instanceof Error?e.message:"تعذر تسجيل الحاج"); } }
  async function saveAgent(e: React.FormEvent) { e.preventDefault(); setMessage(""); setError(""); try { await createParty({ name: agentForm.name, code: agentForm.code || undefined, phone: agentForm.phone || undefined, party_type: "agent", account_id: agentForm.account_id ? Number(agentForm.account_id) : undefined }); setAgentForm({ name: "", code: "", phone: "", account_id: "" }); setMessage("تم تسجيل الوكيل وربطه بالحساب المحاسبي."); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : "تعذر حفظ الوكيل"); } }
  async function saveQuota(e: React.FormEvent) { e.preventDefault(); setMessage(""); setError(""); try { await createHajjQuota({ name_ar: quotaForm.name_ar, season: quotaForm.season, supplier_id: Number(quotaForm.supplier_id), total_units: Number(quotaForm.total_units), unit_cost: Number(quotaForm.unit_cost || 0) }); setMessage("تم إنشاء حصة الحج وربطها بالمورد."); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : "تعذر حفظ حصة الحج"); } }
  async function saveBooking(e: React.FormEvent) { e.preventDefault(); setMessage(""); setError(""); try { const payload:any = { program_id:Number(bookingForm.program_id), pilgrim_id:Number(bookingForm.pilgrim_id), quota_id:Number(bookingForm.quota_id), sale_price:Number(bookingForm.sale_price), supplier_cost:bookingForm.supplier_cost?Number(bookingForm.supplier_cost):undefined }; if (bookingForm.party_mode === "agent") payload.agent_id = Number(bookingForm.agent_id); else payload.customer_id = Number(bookingForm.customer_id); await createHajjBooking(payload); setMessage("تم تسجيل الحاج وربطه بالخدمة والوكيل/العميل وحصة المورد."); setBookingForm(v=>({...v,pilgrim_id:"",agent_id:"",customer_id:"",sale_price:"",supplier_cost:""})); await refresh(); } catch(e){ setError(e instanceof Error?e.message:"تعذر تسجيل الحاج"); } }
  async function post(id:number){ setMessage(""); setError(""); try { await postHajjBooking(id); setMessage(`تم ترحيل حجز الحج #${id} وإنشاء القيد المحاسبي.`); await refresh(); } catch(e){ setError(e instanceof Error?e.message:"تعذر ترحيل الحجز"); } }
  async function collectReceipt(e:React.FormEvent){ e.preventDefault(); setMessage(""); setError(""); try { if(!selectedBooking) throw new Error("اختر خدمة حج للتحصيل"); const payer=selectedBooking.agent_id?agents.find(a=>a.id===selectedBooking.agent_id):customers.find(c=>c.id===selectedBooking.customer_id); if(!payer?.account_id) throw new Error("الوكيل/العميل غير مربوط بحساب محاسبي"); const fa=financial.find(f=>f.id===Number(receiptForm.financial_account_id)); if(!fa?.ledger_account_id) throw new Error("اختر صندوقًا أو بنكًا أو محفظة للاستلام"); const created:any=await createVoucher({voucher_type:"receipt",voucher_date:receiptForm.date,amount:Number(receiptForm.amount),description:receiptForm.description,source_account_id:Number(payer.account_id),destination_account_id:Number(fa.ledger_account_id),linked_service_type:"hajj_booking",linked_service_id:selectedBooking.id}); await postVoucher(created.id); setReceiptForm(v=>({...v,amount:""})); setMessage(`تم تحصيل ${money(receiptForm.amount)} وربطه مباشرة بالحجز #${selectedBooking.id}.`); await refresh(); } catch(e){ setError(e instanceof Error?e.message:"تعذر تسجيل التحصيل"); } }

  return <main className="page"><div className="welcome"><div><span className="eyebrow">قسم الحج</span><h2>إدارة حصة الحج والحجاج والوكلاء</h2><p>كل حاج مرتبط بحصة ومورد وطرف مالي، مع سعر بيع وتكلفة وقيد محاسبي.</p></div></div>
    {(error||message)&&<div className={error?"error-banner":"notice-banner"}>{error||message}</div>}
    <div className="stats compact"><div className="stat"><span>إجمالي الحصة</span><strong>{quotas.reduce((n,q)=>n+q.total_units,0)}</strong><small>حاج</small></div><div className="stat"><span>المستخدم</span><strong>{quotas.reduce((n,q)=>n+q.used_units,0)}</strong><small>حاج</small></div><div className="stat"><span>المتبقي</span><strong>{quotas.reduce((n,q)=>n+q.remaining_units,0)}</strong><small>حاج</small></div><div className="stat"><span>الحجوزات</span><strong>{bookings.length}</strong><small>حجز</small></div></div>
    <section className="panel"><div className="panel-head"><div><h3>تسجيل حاج</h3><p>تسجيل بيانات الحاج أولًا، ثم ربطه لاحقًا بالوكيل والخدمة.</p></div></div><form className="form-grid" onSubmit={savePilgrim}><label><span>الاسم الكامل</span><input value={pilgrimForm.full_name} onChange={e=>setPilgrimForm({...pilgrimForm,full_name:e.target.value})} required/></label><label><span>رقم الجواز</span><input value={pilgrimForm.passport_number} onChange={e=>setPilgrimForm({...pilgrimForm,passport_number:e.target.value})}/></label><label><span>الجنسية</span><input value={pilgrimForm.nationality} onChange={e=>setPilgrimForm({...pilgrimForm,nationality:e.target.value})}/></label><label><span>الهاتف</span><input value={pilgrimForm.phone} onChange={e=>setPilgrimForm({...pilgrimForm,phone:e.target.value})}/></label><div className="form-actions"><button className="primary">حفظ الحاج</button></div></form></section>
    <section className="panel"><div className="panel-head"><div><h3>الوكلاء</h3><p>الوكيل طرف مالي وحسابه يظهر مدينًا بالخدمات، ثم ينخفض رصيده عند سند القبض المرتبط بالخدمة.</p></div></div><form className="form-grid" onSubmit={saveAgent}><label><span>اسم الوكيل</span><input value={agentForm.name} onChange={e=>setAgentForm({...agentForm,name:e.target.value})} required/></label><label><span>رمز الوكيل</span><input value={agentForm.code} onChange={e=>setAgentForm({...agentForm,code:e.target.value})}/></label><label><span>الهاتف</span><input value={agentForm.phone} onChange={e=>setAgentForm({...agentForm,phone:e.target.value})}/></label><label><span>حساب الوكيل</span><select value={agentForm.account_id} onChange={e=>setAgentForm({...agentForm,account_id:e.target.value})}><option value="">اختر الحساب...</option>{accounts.filter(a=>a.account_type==='asset'&&a.is_active).map(a=><option key={a.id} value={a.id}>{a.code} - {a.name_ar}</option>)}</select></label><div className="form-actions"><button className="primary">حفظ الوكيل</button></div></form></section>
    <section className="panel"><div className="panel-head"><div><h3>حصة الحج</h3><p>مثال: وزارة الحج والعمرة — 118 حاجًا — تكلفة الحاج حسب المورد.</p></div></div><form className="form-grid" onSubmit={saveQuota}><label><span>اسم الحصة</span><input value={quotaForm.name_ar} onChange={e=>setQuotaForm({...quotaForm,name_ar:e.target.value})} required/></label><label><span>الموسم</span><input value={quotaForm.season} onChange={e=>setQuotaForm({...quotaForm,season:e.target.value})} required placeholder="1448هـ"/></label><label><span>المورد</span><select value={quotaForm.supplier_id} onChange={e=>setQuotaForm({...quotaForm,supplier_id:e.target.value})} required><option value="">اختر المورد...</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label><span>عدد الحجاج</span><input type="number" min="1" value={quotaForm.total_units} onChange={e=>setQuotaForm({...quotaForm,total_units:e.target.value})} required/></label><label><span>تكلفة الحاج من المورد</span><input type="number" min="0" value={quotaForm.unit_cost} onChange={e=>setQuotaForm({...quotaForm,unit_cost:e.target.value})} required/></label><div className="form-actions"><button className="primary">حفظ الحصة</button></div></form></section>
    <section className="panel"><div className="panel-head"><div><h3>ربط الحاج بالخدمة</h3><p>يمكن أن يكون الطرف وكيلًا أو عميلًا مباشرًا، بينما المورد يأتي من الحصة المختارة.</p></div></div><form className="form-grid" onSubmit={saveBooking}><label><span>برنامج الحج</span><select value={bookingForm.program_id} onChange={e=>setBookingForm({...bookingForm,program_id:e.target.value})} required><option value="">اختر البرنامج...</option>{hajjPrograms.map(p=><option key={p.id} value={p.id}>{p.code} - {p.name_ar}</option>)}</select></label><label><span>الحاج</span><select value={bookingForm.pilgrim_id} onChange={e=>setBookingForm({...bookingForm,pilgrim_id:e.target.value})} required><option value="">اختر الحاج...</option>{pilgrims.map(p=><option key={p.id} value={p.id}>{p.full_name} — {p.passport_number||"بدون جواز"}</option>)}</select></label><label><span>حصة الحج / المورد</span><select value={bookingForm.quota_id} onChange={e=>setBookingForm({...bookingForm,quota_id:e.target.value,supplier_cost:e.target.value?String(quotas.find(q=>q.id===Number(e.target.value))?.unit_cost??""):""})} required><option value="">اختر الحصة...</option>{quotas.filter(q=>q.remaining_units>0).map(q=><option key={q.id} value={q.id}>{q.name_ar} — المتبقي {q.remaining_units}</option>)}</select></label><label><span>نوع الطرف</span><select value={bookingForm.party_mode} onChange={e=>setBookingForm({...bookingForm,party_mode:e.target.value,agent_id:"",customer_id:""})}><option value="agent">وكيل</option><option value="customer">عميل مباشر</option></select></label>{bookingForm.party_mode==="agent"?<label><span>الوكيل</span><select value={bookingForm.agent_id} onChange={e=>setBookingForm({...bookingForm,agent_id:e.target.value})} required><option value="">اختر الوكيل...</option>{agents.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>:<label><span>العميل</span><select value={bookingForm.customer_id} onChange={e=>setBookingForm({...bookingForm,customer_id:e.target.value})} required><option value="">اختر العميل...</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<label><span>سعر البيع على الطرف</span><input type="number" min="0.01" value={bookingForm.sale_price} onChange={e=>setBookingForm({...bookingForm,sale_price:e.target.value})} required/></label><label><span>تكلفة المورد</span><input type="number" min="0" value={bookingForm.supplier_cost} onChange={e=>setBookingForm({...bookingForm,supplier_cost:e.target.value})}/></label><div className="form-actions"><button className="primary">تسجيل الخدمة</button>{selectedQuota&&<span className="muted">تكلفة الحصة الافتراضية: {money(selectedQuota.unit_cost)}</span>}</div></form></section>
    <section className="panel"><div className="panel-head"><div><h3>سند قبض مرتبط بخدمة الحج</h3><p>السند يحدد الحجز ويخفض المتبقي تلقائيًا، ولا يمكن ترحيله على طرف آخر.</p></div></div><form className="form-grid" onSubmit={collectReceipt}><label><span>خدمة الحج</span><select value={receiptForm.booking_id} onChange={e=>setReceiptForm({...receiptForm,booking_id:e.target.value})} required><option value="">اختر الحجز...</option>{bookings.filter(b=>b.status==='confirmed'&&Number(b.remaining_amount)>0).map(b=><option key={b.id} value={b.id}>حجز #{b.id} — {money(b.remaining_amount)} متبقي</option>)}</select></label><label><span>حساب الاستلام</span><select value={receiptForm.financial_account_id} onChange={e=>setReceiptForm({...receiptForm,financial_account_id:e.target.value})} required><option value="">اختر صندوق/بنك/محفظة...</option>{financial.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label><span>المبلغ</span><input type="number" min="0.01" value={receiptForm.amount} onChange={e=>setReceiptForm({...receiptForm,amount:e.target.value})} required/></label><label><span>التاريخ</span><input type="date" value={receiptForm.date} onChange={e=>setReceiptForm({...receiptForm,date:e.target.value})} required/></label><label><span>البيان</span><input value={receiptForm.description} onChange={e=>setReceiptForm({...receiptForm,description:e.target.value})} required/><div className="form-actions"><button className="primary">حفظ وترحيل سند القبض</button>{selectedBooking&&<span className="muted">المتبقي: {money(selectedBooking.remaining_amount)}{selectedAgent?` • الوكيل: ${selectedAgent.name}`:""}</span>}</div></label></form></section>
    <section className="panel"><div className="panel-head"><h3>حصص الحج المسجلة</h3></div><div className="table-wrap"><table><thead><tr><th>الحصة</th><th>الموسم</th><th>المورد</th><th>الإجمالي</th><th>المستخدم</th><th>المتبقي</th><th>التكلفة</th></tr></thead><tbody>{quotas.map(q=><tr key={q.id}><td>{q.name_ar}</td><td>{q.season}</td><td>{suppliers.find(s=>s.id===q.supplier_id)?.name||q.supplier_id}</td><td>{q.total_units}</td><td>{q.used_units}</td><td>{q.remaining_units}</td><td>{money(q.unit_cost)}</td></tr>)}</tbody></table></div></section>
    <section className="panel"><div className="panel-head"><div><h3>سجل حجاج الحج</h3><p>عند الترحيل: الطرف مدين، إيراد الحج دائن، وتكلفة المورد تسجل على المورد.</p></div></div><div className="table-wrap"><table><thead><tr><th>#</th><th>الحاج</th><th>الوكيل/العميل</th><th>البيع</th><th>التكلفة</th><th>المدفوع</th><th>المتبقي</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{bookings.map(b=><tr key={b.id}><td>{b.id}</td><td>{pilgrims.find(p=>p.id===b.pilgrim_id)?.full_name||b.pilgrim_id}</td><td>{b.agent_id?agents.find(a=>a.id===b.agent_id)?.name||`وكيل #${b.agent_id}`:customers.find(c=>c.id===b.customer_id)?.name||`عميل #${b.customer_id}`}</td><td>{money(b.sale_price)}</td><td>{money(b.supplier_cost)}</td><td>{money(b.paid_amount)}</td><td>{money(b.remaining_amount)}</td><td>{b.status==='reserved'?'محجوز':b.status==='confirmed'?'مرحّل':'ملغى'}</td><td>{b.status==='reserved'&&<button className="link" onClick={()=>post(b.id)}>ترحيل</button>}</td></tr>)}</tbody></table></div></section>
  </main>;
}
