import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import "./styles.css";
import {getMe,getParties,getPilgrims,getPrograms,getSettings,login,type Pilgrim,type Program} from "./api";
import HajjPage from "./HajjPageTabs";
import UmrahPage from "./UmrahPage";
import ServicePage from "./ServicePage";
import AccountsPage from "./AccountsPage";
import FinancialAccountsPanel from "./FinancialAccountsPanel";
import SupplierPaymentPanel from "./SupplierPaymentPanel";
import SettingsPage from "./SettingsPage";
import AccountingControlsPage from "./AccountingControlsPage";
import JournalsPage from "./JournalsPage";
import ExpensesPage from "./ExpensesPage";
import ArApPage from "./ArApPage";
import SystemTree from "./SystemTree";
type ExtraService="visit"|"work_visa";
function App(){const [token,setToken]=useState(localStorage.getItem("accounting_token"));const savedBranding=(()=>{try{return JSON.parse(localStorage.getItem("accounting_branding")||"null")}catch{return null}})();const [active,setActive]=useState("hajj"),[programs,setPrograms]=useState<Program[]>([]),[pilgrims,setPilgrims]=useState<Pilgrim[]>([]),[customers,setCustomers]=useState<any[]>([]),[suppliers,setSuppliers]=useState<any[]>([]),[agents,setAgents]=useState<any[]>([]),[me,setMe]=useState<any>(null),[branding,setBranding]=useState(savedBranding||{name:"نظام إدارة الحج والعمرة والسفر",logo:"",phone:"",address:""});const title=({hajj:"الحج",umrah:"العمرة",flight:"الطيران",buses:"الباصات",accounts:"الدليل المحاسبي",journals:"القيود اليومية",expenses:"المصروفات",ar_ap:"الذمم والمدفوعات",accounting_controls:"الضبط المحاسبي",settings:"الإعدادات",extra_visit:"الزيارات",extra_work_visa:"فيز العمل"} as Record<string,string>)[active]??"الحج";
useEffect(()=>{if(!token)return;Promise.allSettled([getPrograms(),getPilgrims(),getParties("customer"),getParties("supplier"),getParties("agent"),getMe(),getSettings()]).then(r=>{if(r[0].status==="fulfilled")setPrograms(r[0].value);if(r[1].status==="fulfilled")setPilgrims(r[1].value);if(r[2].status==="fulfilled")setCustomers(r[2].value);if(r[3].status==="fulfilled")setSuppliers(r[3].value);if(r[4].status==="fulfilled")setAgents(r[4].value);if(r[5].status==="fulfilled")setMe(r[5].value);if(r[6].status==="fulfilled"){const s=Object.fromEntries(r[6].value.map(x=>[x.key,x.value]));const nextBranding={name:s.company_name||"نظام إدارة الحج والعمرة والسفر",logo:s.company_logo_url||"",phone:s.company_phone||"",address:s.company_address||""};setBranding(nextBranding);localStorage.setItem("accounting_branding",JSON.stringify(nextBranding));}})},[token]);
function logout(){localStorage.removeItem("accounting_token");setToken(null);setMe(null)}function openExtraService(kind:ExtraService){setActive(kind==="visit"?"extra_visit":"extra_work_visa")}
function navigateTree(module:string,target?:string){setActive(module);if(target){window.setTimeout(()=>{const headings=Array.from(document.querySelectorAll(".workspace-main h2,.workspace-main h3"));const heading=headings.find(h=>h.textContent?.replace(/\s+/g," ").trim().includes(target));heading?.scrollIntoView({behavior:"smooth",block:"start"});},120)}}
if(!token)return <LoginPage onLogin={t=>{localStorage.setItem("accounting_token",t);setToken(t)}}/>;
return <div className="shell" dir="rtl"><section className="content"><header className="topbar"><div><h1>{title}</h1><p>{branding.name} — نظام محاسبي وتشغيلي</p></div><div className="top-actions"><button className="icon-btn" title="تسجيل الخروج" onClick={logout}>⇥</button>{me&&<div className="user-chip">{branding.logo?<img src={branding.logo} alt="شعار الوكالة" className="user-logo"/>:<span>م</span>}<div><b>{me.full_name}</b><small>{me.username}</small></div></div>}</div></header><div className="workspace-layout"><SystemTree activeModule={active as any} onNavigate={navigateTree}/><div className="workspace-main">{active==="hajj"&&<HajjPage programs={programs} pilgrims={pilgrims} suppliers={suppliers} customers={customers}/>} {active==="umrah"&&<UmrahPage programs={programs} pilgrims={pilgrims} suppliers={suppliers} customers={customers}/>} {active==="flight"&&<ServicePage serviceType="flight" title="الطيران" icon="✈️" pilgrims={pilgrims} suppliers={suppliers} customers={customers} agents={agents}/>} {active==="buses"&&<ServicePage serviceType="bus" title="الباصات" icon="🚌" pilgrims={pilgrims} suppliers={suppliers} customers={customers} agents={agents}/>} {(active==="extra_visit"||active==="extra_work_visa")&&<ServicePage serviceType={active==="extra_visit"?"visit":"work_visa"} title={active==="extra_visit"?"الزيارات":"فيز العمل"} icon={active==="extra_visit"?"🗺️":"🪪"} pilgrims={pilgrims} suppliers={suppliers} customers={customers} agents={agents}/>} {active==="accounts"&&<><AccountsPage/><FinancialAccountsPanel/><SupplierPaymentPanel/></>} {active==="journals"&&<JournalsPage/>} {active==="expenses"&&<ExpensesPage/>} {active==="ar_ap"&&<ArApPage/>} {active==="accounting_controls"&&<AccountingControlsPage/>} {active==="settings"&&<SettingsPage onOpenExtraService={openExtraService} onBrandingChange={setBranding}/>}</div></div></section></div>}
function LoginPage({onLogin}:{onLogin:(token:string)=>void}){const savedBranding=(()=>{try{return JSON.parse(localStorage.getItem("accounting_branding")||"null")}catch{return null}})();const branding=savedBranding||{name:"نظام إدارة الحج والعمرة والسفر",logo:""};const [username,setUsername]=useState("admin"),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await login(username,password);onLogin(r.access_token)}catch(e){setError(e instanceof Error?e.message:"تعذر تسجيل الدخول")}finally{setBusy(false)}}return <div className="login-shell" dir="rtl"><form className="login-card" onSubmit={submit}><div className="brand-mark">{branding.logo?<img src={branding.logo} alt="شعار الوكالة" style={{width:"100%",height:"100%",objectFit:"contain",borderRadius:12}}/>:<span>م</span>}</div><h1>{branding.name}</h1><p>نظام المحاسبة والتشغيل للوكالات</p><label>اسم المستخدم<input value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>كلمة المرور<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="error-banner">{error}</div>}<button className="primary" disabled={busy}>{busy?"جارٍ الدخول…":"دخول إلى النظام"}</button></form></div>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
