import React,{useEffect,useMemo,useState} from "react";
import {createVoucher,getFinancial,getHajjBookings,getParties,getServices,getUmrahBookings,postVoucher} from "./api";

const money=(v:string|number)=>Number(v||0).toLocaleString("ar-YE",{minimumFractionDigits:2,maximumFractionDigits:2});
type Payable={key:string;linked_service_type:"hajj_booking"|"umrah_booking"|"service_order";id:number;service:string;reference:string;supplier_id:number;cost:number;paid:number;remaining:number;details:string};

export default function SupplierPaymentPanel(){
  const [rows,setRows]=useState<Payable[]>([]),[suppliers,setSuppliers]=useState<any[]>([]),[financial,setFinancial]=useState<any[]>([]),[selected,setSelected]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const [form,setForm]=useState({financial_id:"",manual_voucher_number:"",amount:"",date:new Date().toISOString().slice(0,10),description:"سداد مستحق مورد"});
  const chosen=rows.find(r=>r.key===selected);
  async function refresh(){
    try{
      const [h0,u0,f,a,flight,bus,visit,workVisa]=await Promise.all([getHajjBookings(),getUmrahBookings(),getFinancial(),getParties("supplier"),getServices("flight"),getServices("bus"),getServices("visit"),getServices("work_visa")]);
      const h=h0 as any[]; const u=u0 as any[];
      const smap=new Map(a.map((s:any)=>[s.id,s.name]));
      const list:Payable[]=[];
      for(const x of h.filter((r:any)=>r.status==="posted"&&Number(r.supplier_cost)>Number(r.supplier_paid_amount||0))) list.push({key:`hajj-${x.id}`,linked_service_type:"hajj_booking",id:x.id,service:"الحج",reference:`حجز حج #${x.id}`,supplier_id:Number(x.supplier_id),cost:Number(x.supplier_cost),paid:Number(x.supplier_paid_amount||0),remaining:Number(x.supplier_cost)-Number(x.supplier_paid_amount||0),details:String(smap.get(x.supplier_id)||`مورد #${x.supplier_id}`)});
      for(const x of u.filter((r:any)=>r.status==="posted"&&Number(r.supplier_cost)>Number(r.supplier_paid_amount||0))) list.push({key:`umrah-${x.id}`,linked_service_type:"umrah_booking",id:x.id,service:"العمرة",reference:`حجز عمرة #${x.id}`,supplier_id:Number(x.supplier_id),cost:Number(x.supplier_cost),paid:Number(x.supplier_paid_amount||0),remaining:Number(x.supplier_cost)-Number(x.supplier_paid_amount||0),details:String(smap.get(x.supplier_id)||`مورد #${x.supplier_id}`)});
      const generic=[...(flight as any[]),...(bus as any[]),...(visit as any[]),...(workVisa as any[])];
      for(const x of generic.filter((r:any)=>r.status==="posted"&&r.supplier_id&&Number(r.supplier_cost)>Number(r.supplier_paid_amount||0))) list.push({key:`service-${x.service_type}-${x.id}`,linked_service_type:"service_order",id:x.id,service:x.service_type==="flight"?"الطيران":x.service_type==="bus"?"الباصات":x.service_type==="visit"?"الزيارات":"فيز العمل",reference:x.reference_no,supplier_id:Number(x.supplier_id),cost:Number(x.supplier_cost),paid:Number(x.supplier_paid_amount||0),remaining:Number(x.supplier_cost)-Number(x.supplier_paid_amount||0),details:String(smap.get(x.supplier_id)||`مورد #${x.supplier_id}`)});
      setSuppliers(a);setFinancial(f);setRows(list);setError("");
    }catch(e){setError(e instanceof Error?e.message:"تعذر تحميل مستحقات الموردين")}
  }
  useEffect(()=>{refresh()},[]);
  useEffect(()=>{if(!rows.some(r=>r.key===selected))setSelected(rows[0]?.key||"")},[rows,selected]);
  const stats=useMemo(()=>({count:rows.length,total:rows.reduce((n,r)=>n+r.cost,0),paid:rows.reduce((n,r)=>n+r.paid,0),remaining:rows.reduce((n,r)=>n+r.remaining,0)}),[rows]);
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{if(!chosen)throw new Error("اختر الخدمة المستحقة للمورد");const fa=financial.find(f=>f.id===Number(form.financial_id));if(!fa?.ledger_account_id)throw new Error("اختر حساب الدفع الصحيح");const supplier=suppliers.find(s=>s.id===chosen.supplier_id);if(!supplier?.account_id)throw new Error("المورد غير مربوط بحساب محاسبي");const amount=Number(form.amount);if(amount<=0)throw new Error("أدخل مبلغًا صحيحًا");if(amount>chosen.remaining)throw new Error("المبلغ أكبر من المتبقي للمورد");const v=await createVoucher({manual_voucher_number:form.manual_voucher_number.trim()||undefined,voucher_type:"payment",voucher_date:form.date,amount,description:form.description,source_account_id:Number(fa.ledger_account_id),destination_account_id:Number(supplier.account_id),linked_service_type:chosen.linked_service_type,linked_service_id:chosen.id});await postVoucher(v.id);setForm(x=>({...x,manual_voucher_number:"",amount:""}));setMessage(`تم سداد ${money(amount)} للمورد وربطه بـ ${chosen.service} ${chosen.reference}.`);await refresh()}catch(e){setError(e instanceof Error?e.message:"تعذر تسجيل سداد المورد")}finally{setBusy(false)}}
  return <>
    {(error||message)&&<div className={error?"error-banner":"notice-banner"}>{error||message}</div>}
    <div className="stats compact" style={{marginTop:18}}><div className="stat"><span>الخدمات المستحقة</span><strong>{stats.count}</strong></div><div className="stat"><span>إجمالي التكلفة</span><strong>{money(stats.total)}</strong><small>ريال</small></div><div className="stat"><span>المسدد</span><strong>{money(stats.paid)}</strong><small>ريال</small></div><div className="stat"><span>المتبقي</span><strong>{money(stats.remaining)}</strong><small>ريال</small></div></div>
    <section className="panel"><div className="panel-head"><div><h3>سداد مستحقات الموردين</h3><p>السداد يخصم من المستحق على المورد ويُربط بالخدمة نفسها لأغراض المراجعة.</p></div></div><form className="form-grid" onSubmit={save}><label className="full"><span>الخدمة والمورد</span><select value={selected} onChange={e=>setSelected(e.target.value)} required><option value="">اختر الخدمة...</option>{rows.map(r=><option key={r.key} value={r.key}>{r.service} — {r.reference} — {r.details} — متبقي {money(r.remaining)}</option>)}</select></label><label><span>رقم السند اليدوي (اختياري)</span><input value={form.manual_voucher_number} onChange={e=>setForm({...form,manual_voucher_number:e.target.value})} placeholder="اتركه فارغًا للترقيم التلقائي"/></label><label><span>حساب الدفع</span><select value={form.financial_id} onChange={e=>setForm({...form,financial_id:e.target.value})} required><option value="">اختر صندوق/بنك/محفظة...</option>{financial.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label><span>المبلغ</span><input type="number" min="0.01" step="0.01" max={chosen?.remaining} value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} required/></label><label><span>التاريخ</span><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} required/></label><label className="full"><span>البيان</span><input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required/></label><div className="form-actions"><button className="primary" disabled={busy}>{busy?"جارٍ الترحيل…":"حفظ وترحيل سند الصرف"}{chosen?` • المتبقي ${money(chosen.remaining)}`:""}</button></div></form></section>
    <section className="panel"><div className="panel-head"><div><h3>المستحقات المفتوحة</h3><p>الخدمات الظاهرة هنا لها تكلفة مورد لم تُسدَّد بالكامل.</p></div></div><div className="table-wrap"><table><thead><tr><th>الخدمة</th><th>المرجع</th><th>المورد</th><th>التكلفة</th><th>المسدد</th><th>المتبقي</th></tr></thead><tbody>{rows.map(r=><tr key={r.key}><td>{r.service}</td><td>{r.reference}</td><td>{r.details}</td><td>{money(r.cost)}</td><td>{money(r.paid)}</td><td>{money(r.remaining)}</td></tr>)}</tbody></table></div></section>
  </>;
}
