import React,{useState} from "react";
type ModuleId="hajj"|"umrah"|"flight"|"buses"|"accounts"|"journals"|"expenses"|"ar_ap"|"accounting_controls"|"settings";
type Node={id:string;label:string;target?:string;children?:Node[]};
const TREE:Node[]=[
{id:"hajj",label:"الحج",children:[{id:"h1",label:"التهيئة",children:[{id:"h11",label:"البرامج",target:"البرامج"},{id:"h12",label:"الحصص",target:"الحصص"}]},{id:"h2",label:"المدخلات",children:[{id:"h21",label:"المعتمرون",target:"المعتمرون"},{id:"h22",label:"الوكلاء",target:"الوكلاء"}]},{id:"h3",label:"العمليات",children:[{id:"h31",label:"الحجوزات",target:"الحجوزات"},{id:"h32",label:"التحصيل",target:"التحصيل"}]},{id:"h4",label:"التقارير",children:[{id:"h41",label:"كشف حساب الأطراف",target:"كشف حساب طرف"}]}]},
{id:"umrah",label:"العمرة",children:[{id:"u1",label:"المدخلات",children:[{id:"u11",label:"تسجيل خدمة العمرة",target:"تسجيل خدمة عمرة"}]},{id:"u2",label:"العمليات",children:[{id:"u21",label:"الترحيل والإلغاء",target:"سجل خدمات العمرة"},{id:"u22",label:"سند القبض",target:"سند قبض مرتبط بخدمة العمرة"}]},{id:"u3",label:"التقارير",children:[{id:"u31",label:"سجل خدمات العمرة",target:"سجل خدمات العمرة"}]}]},
{id:"flight",label:"الطيران",children:[{id:"f1",label:"المدخلات",children:[{id:"f11",label:"تسجيل الطيران",target:"تسجيل الطيران"}]},{id:"f2",label:"العمليات",children:[{id:"f21",label:"الترحيل والإلغاء",target:"سجل الطيران"},{id:"f22",label:"التحصيل",target:"سند قبض مرتبط بـ الطيران"}]},{id:"f3",label:"التقارير",children:[{id:"f31",label:"سجل الطيران",target:"سجل الطيران"}]}]},
{id:"buses",label:"الباصات",children:[{id:"b1",label:"المدخلات",children:[{id:"b11",label:"تسجيل الباصات",target:"تسجيل الباصات"}]},{id:"b2",label:"العمليات",children:[{id:"b21",label:"الترحيل والإلغاء",target:"سجل الباصات"},{id:"b22",label:"التحصيل",target:"سند قبض مرتبط بـ الباصات"}]},{id:"b3",label:"التقارير",children:[{id:"b31",label:"سجل الباصات",target:"سجل الباصات"}]}]},
{id:"accounts",label:"الدليل المحاسبي",children:[{id:"a1",label:"تهيئة الأستاذ العام",children:[{id:"a11",label:"دليل الحسابات",target:"دليل الحسابات"}]},{id:"a2",label:"المدخلات",children:[{id:"a21",label:"الموردون",target:"الموردون"},{id:"a22",label:"الصناديق والبنوك والمحافظ",target:"الصناديق والبنوك والمحافظ"}]},{id:"a3",label:"العمليات",children:[{id:"a31",label:"كشف حساب طرف",target:"كشف حساب طرف"},{id:"a32",label:"سداد مستحقات الموردين",target:"سداد مستحقات الموردين"}]},{id:"a4",label:"التقارير",children:[{id:"a41",label:"الملخص المالي",target:"الملخص المالي"},{id:"a42",label:"اليومية",target:"اليومية"},{id:"a43",label:"ميزان المراجعة",target:"ميزان المراجعة"},{id:"a44",label:"الأرباح والخسائر",target:"الأرباح والخسائر"},{id:"a45",label:"الأستاذ العام",target:"الأستاذ العام"}]}]},
{id:"journals",label:"القيود اليومية",children:[{id:"j1",label:"العمليات",children:[{id:"j11",label:"قيد يومي جديد",target:"قيد يومي جديد"},{id:"j12",label:"ترحيل القيود",target:"القيود المسجلة"}]}]},
{id:"expenses",label:"المصروفات",children:[{id:"e1",label:"تسجيل المصروفات وترحيلها",target:"إدارة المصروفات"}]},
{id:"ar_ap",label:"الذمم والمدفوعات",children:[{id:"r1",label:"الفواتير",target:"الفواتير"},{id:"r2",label:"القبض والصرف",target:"المدفوعات"},{id:"r3",label:"أعمار الذمم",target:"أعمار الذمم"}]},
{id:"accounting_controls",label:"الضبط المحاسبي",children:[{id:"c1",label:"الأبعاد والفترات وسجل التدقيق",target:"الضبط المحاسبي"}]},
{id:"settings",label:"الإعدادات",children:[{id:"s1",label:"بيانات الوكالة",target:"الإعدادات العامة"},{id:"s2",label:"ربط الحسابات",target:"ربط الحسابات"},{id:"s3",label:"الفروع",target:"الفروع"},{id:"s4",label:"المستخدمون",target:"المستخدمون"},{id:"s5",label:"الأدوار والصلاحيات",target:"الأدوار والصلاحيات"},{id:"s6",label:"العملات",target:"العملات"},{id:"s7",label:"الخدمات الإضافية",target:"الخدمات الإضافية"}]}
];
function TreeNode({node,activeModule,onNavigate,level=0}:{node:Node;activeModule:ModuleId;onNavigate:(m:ModuleId,t?:string)=>void;level?:number}){const[open,setOpen]=useState(level===0&&node.id===activeModule);const has=!!node.children?.length;const module=node.id===activeModule;return <div className="tree-node"><button className={`tree-row ${module?"active":""}`} style={{paddingInlineStart:10+level*18}} onClick={()=>{if(node.target){onNavigate(activeModule,node.target);return;}if(["hajj","umrah","flight","buses","accounts","journals","expenses","ar_ap","accounting_controls","settings"].includes(node.id)){onNavigate(node.id as ModuleId);return;}if(has)setOpen(v=>!v)}}><span className="tree-caret">{has?(open?"⌄":"‹"):"•"}</span><span>{node.label}</span></button>{open&&node.children?.map(c=><TreeNode key={c.id} node={c} activeModule={activeModule} onNavigate={onNavigate} level={level+1}/>)}</div>}
export default function SystemTree({activeModule,onNavigate}:{activeModule:ModuleId;onNavigate:(m:ModuleId,t?:string)=>void}){return <aside className="system-tree panel"><div className="tree-head"><span className="eyebrow">التنقل</span><h3>شجرة النظام</h3><p>تهيئة ← مدخلات ← عمليات ← تقارير</p></div><div className="tree-body">{TREE.map(n=><TreeNode key={n.id} node={n} activeModule={activeModule} onNavigate={onNavigate}/>)}</div></aside>}
